{% macro create_sp_streamline_dev_permissions() -%}
CREATE OR REPLACE PROCEDURE streamline.streamline_dev_permissions(dev_db_name STRING)
RETURNS BOOLEAN
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    BEGIN TRANSACTION;

    -- Create databases and schemas
    EXECUTE IMMEDIATE 'CREATE DATABASE IF NOT EXISTS ' || :dev_db_name;
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :dev_db_name || '.BRONZE';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :dev_db_name || '.SILVER';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :dev_db_name || '.STREAMLINE';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS ' || :dev_db_name || '._INTERNAL';
    EXECUTE IMMEDIATE 'CREATE SCHEMA IF NOT EXISTS STREAMLINE.' || :dev_db_name;

    -- Grant ownership on schemas, tables, views, and functions
    EXECUTE IMMEDIATE 'GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE ' || :dev_db_name || ' TO ROLE INTERNAL_DEV COPY CURRENT GRANTS';
    EXECUTE IMMEDIATE 'GRANT OWNERSHIP ON ALL FUNCTIONS IN SCHEMA ' || :dev_db_name || '.STREAMLINE TO ROLE INTERNAL_DEV COPY CURRENT GRANTS';
    EXECUTE IMMEDIATE 'GRANT OWNERSHIP ON ALL VIEWS IN SCHEMA ' || :dev_db_name || '.STREAMLINE TO ROLE INTERNAL_DEV COPY CURRENT GRANTS';
    EXECUTE IMMEDIATE 'GRANT OWNERSHIP ON ALL TABLES IN SCHEMA ' || :dev_db_name || '.STREAMLINE TO ROLE INTERNAL_DEV COPY CURRENT GRANTS';

    -- Grant ownership on future schemas, tables, views, and functions
    EXECUTE IMMEDIATE 'GRANT OWNERSHIP ON FUTURE SCHEMAS IN DATABASE ' || :dev_db_name || ' TO ROLE INTERNAL_DEV COPY CURRENT GRANTS';
    EXECUTE IMMEDIATE 'GRANT OWNERSHIP ON FUTURE FUNCTIONS IN SCHEMA ' || :dev_db_name || '.STREAMLINE TO ROLE INTERNAL_DEV COPY CURRENT GRANTS';
    EXECUTE IMMEDIATE 'GRANT OWNERSHIP ON FUTURE VIEWS IN SCHEMA ' || :dev_db_name || '.STREAMLINE TO ROLE INTERNAL_DEV COPY CURRENT GRANTS';
    EXECUTE IMMEDIATE 'GRANT OWNERSHIP ON FUTURE TABLES IN SCHEMA ' || :dev_db_name || '.STREAMLINE TO ROLE INTERNAL_DEV COPY CURRENT GRANTS';

    -- Grant ownership on the database
    EXECUTE IMMEDIATE 'GRANT OWNERSHIP ON DATABASE ' || :dev_db_name || ' TO ROLE INTERNAL_DEV COPY CURRENT GRANTS';

    COMMIT;
    RETURN TRUE;
END;
$$;
{%- endmacro %}