version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'datascience' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: address_tags
      - name: dim_dates
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'datascience' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: number_sequence
  - name: bronze_streamline
    database: streamline
    schema: datascience_dev
    tables:
      - name: blocks_tx
      - name: quantum_poc_aptos_blocks_tx
  - name: github_actions
    database: "{{ target.database }}"
    schema: github_actions
    tables:
      - name: workflows
  - name: avalanche_gold_core
    database: "{{ 'avalanche' if target.database == 'datascience' else 'avalanche_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: dim_contracts
      - name: fact_transactions
      - name: ez_token_transfers
      - name: ez_native_transfers
      - name: ez_decoded_event_logs
  - name: avalanche_gold_defi
    database: "{{ 'avalanche' if target.database == 'datascience' else 'avalanche_dev' }}"
    schema: defi
    tables:
      - name: ez_bridge_activity
      - name: ez_dex_swaps
      - name: dim_dex_liquidity_pools
  - name: avalanche_gold_nft
    database: "{{ 'avalanche' if target.database == 'datascience' else 'avalanche_dev' }}"
    schema: nft
    tables:
      - name: ez_nft_sales
  - name: ethereum_gold_core
    database: "{{ 'ethereum' if target.database == 'datascience' else 'ethereum_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: dim_contracts
      - name: fact_transactions
      - name: ez_native_transfers
      - name: ez_token_transfers
      - name: ez_decoded_event_logs
  - name: ethereum_gold_defi
    database: "{{ 'ethereum' if target.database == 'datascience' else 'ethereum_dev' }}"
    schema: defi
    tables:
      - name: ez_bridge_activity
      - name: ez_dex_swaps
      - name: dim_dex_liquidity_pools
  - name: ethereum_gold_nft
    database: "{{ 'ethereum' if target.database == 'datascience' else 'ethereum_dev' }}"
    schema: nft
    tables:
      - name: ez_nft_sales
  - name: base_gold_core
    database: "{{ 'base' if target.database == 'datascience' else 'base_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: dim_contracts
      - name: fact_transactions
      - name: ez_native_transfers
      - name: ez_token_transfers
      - name: ez_decoded_event_logs
  - name: base_gold_defi
    database: "{{ 'base' if target.database == 'datascience' else 'base_dev' }}"
    schema: defi
    tables:
      - name: ez_bridge_activity
      - name: ez_dex_swaps
      - name: dim_dex_liquidity_pools
  - name: base_gold_nft
    database: "{{ 'base' if target.database == 'datascience' else 'base_dev' }}"
    schema: nft
    tables:
      - name: ez_nft_sales
  - name: polygon_gold_core
    database: "{{ 'polygon' if target.database == 'datascience' else 'polygon_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: dim_contracts
      - name: fact_transactions
      - name: ez_native_transfers
      - name: ez_decoded_event_logs
      - name: ez_token_transfers
  - name: polygon_gold_defi
    database: "{{ 'polygon' if target.database == 'datascience' else 'polygon_dev' }}"
    schema: defi
    tables:
      - name: ez_bridge_activity
      - name: ez_dex_swaps
      - name: dim_dex_liquidity_pools
  - name: polygon_gold_nft
    database: "{{ 'polygon' if target.database == 'datascience' else 'polygon_dev' }}"
    schema: nft
    tables:
      - name: ez_nft_sales
  - name: optimism_gold_core
    database: "{{ 'optimism' if target.database == 'datascience' else 'optimism_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: dim_contracts
      - name: fact_transactions
      - name: ez_native_transfers
      - name: ez_token_transfers
      - name: ez_decoded_event_logs
  - name: optimism_gold_defi
    database: "{{ 'optimism' if target.database == 'datascience' else 'optimism_dev' }}"
    schema: defi
    tables:
      - name: ez_bridge_activity
      - name: ez_dex_swaps
      - name: dim_dex_liquidity_pools
  - name: optimism_gold_nft
    database: "{{ 'optimism' if target.database == 'datascience' else 'optimism_dev' }}"
    schema: nft
    tables:
      - name: ez_nft_sales
  - name: arbitrum_gold_core
    database: "{{ 'arbitrum' if target.database == 'datascience' else 'arbitrum_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: dim_contracts
      - name: fact_transactions
      - name: ez_native_transfers
      - name: ez_token_transfers
      - name: ez_decoded_event_logs
  - name: arbitrum_gold_defi
    database: "{{ 'arbitrum' if target.database == 'datascience' else 'arbitrum_dev' }}"
    schema: defi
    tables:
      - name: ez_bridge_activity
      - name: ez_dex_swaps
      - name: dim_dex_liquidity_pools
      - name: ez_decoded_event_logs
  - name: aptos_gold_core
    database: "{{ 'aptos' if target.database == 'datascience' else 'aptos_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: dim_tokens
      - name: fact_transactions
      - name: fact_transfers
      - name: fact_events
  - name: aptos_gold_defi
    database: "{{ 'aptos' if target.database == 'datascience' else 'aptos_dev' }}"
    schema: defi
    tables:
      - name: fact_bridge_activity
  - name: aptos_gold_nft
    database: "{{ 'aptos' if target.database == 'datascience' else 'aptos_dev' }}"
    schema: nft
    tables:
      - name: ez_nft_sales
  - name: near_gold_core
    database: "{{ 'near' if target.database == 'datascience' else 'near_dev' }}"
    schema: core
    tables:
      - name: dim_address_labels
      - name: fact_transactions
      - name: dim_ft_contract_metadata
      - name: ez_token_transfers
  - name: near_gold_defi
    database: "{{ 'near' if target.database == 'datascience' else 'near_dev' }}"
    schema: defi
    tables:
      - name: ez_bridge_activity
      - name: ez_dex_swaps
  - name: near_gold_nft
    database: "{{ 'near' if target.database == 'datascience' else 'near_dev' }}"
    schema: nft
    tables:
      - name: ez_nft_sales
      - name: fact_nft_mints
  - name: near_gold_gov
    database: "{{ 'near' if target.database == 'datascience' else 'near_dev' }}"
    schema: gov
    tables:
      - name: fact_staking_actions
  - name: blast_gold_core
    database: "{{ 'blast' if target.database == 'datascience' else 'blast_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: dim_contracts
      - name: fact_transactions
      - name: ez_native_transfers
      - name: ez_token_transfers
      - name: ez_decoded_event_logs



