version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'M1' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: address_tags
      - name: dim_dates
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'M1' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: asset_metadata_coin_market_cap
      - name: asset_metadata_coin_gecko
      - name: hourly_prices_coin_market_cap
      - name: hourly_prices_coin_gecko
      - name: number_sequence
      - name: labels_combined
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "M1_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "M1" }}
    tables:
      - name: blocks_tx
      - name: transactions
      - name: evm_blocks
      - name: evm_transactions
      - name: evm_confirm_blocks
      - name: evm_receipts
      - name: evm_traces
      - name: evm_decoded_logs
  - name: github_actions
    database: M1
    schema: github_actions
    tables:
      - name: workflows
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis